(function (lib, img, cjs, ss, an) {

var p; // shortcut to reference prototypes
lib.ssMetadata = [];


// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1059,249);


(lib.logo = function() {
	this.initialize(img.logo);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,169,23);


(lib.prod = function() {
	this.initialize(img.prod);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,96,194);


(lib.SelectiveColor1 = function() {
	this.initialize(img.SelectiveColor1);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,142,105);


(lib.spot_light = function() {
	this.initialize(img.spot_light);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,307,270);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.logo_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.logo();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.logo_1, new cjs.Rectangle(0,0,169,23), null);


(lib.light = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["rgba(255,255,255,0)","rgba(255,255,255,0.8)","rgba(255,255,255,0)"],[0,0.502,1],-145,0,145,0).s().p("A2pX1MAAAgvpMAtTAAAMAAAAvpg");
	this.shape.setTransform(15,137.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.light, new cjs.Rectangle(-130,-15,290,305), null);


(lib.spot_light_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.spot_light();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.spot_light_1, new cjs.Rectangle(0,0,307,270), null);


(lib.SelectiveColor1_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.SelectiveColor1();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.SelectiveColor1_1, new cjs.Rectangle(0,0,142,105), null);


(lib.ct3txt_3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGVA/QAJAAAJgBQAJgBAJgDQgJgFgMgIIAEgGQAJAHAQAIIAGgCIANgIQAGgEAEgFIhCAAIAAgHIBJAAIAFAEIgOAPIgRALQAKACAZADIgCAHQgJAAgKgCIgSgFIgFgBIgOAFIgNADIgQABgAqOBCIAKgMQAEgHACgIIAHACIgIARQgEAHgFAFgAphBEIAEgaIAHABQgBAKgEARgADIBFIAAhVIgJAOIgFgFIAJgOIAHgOQADgIACgIIAEgRIAHACIgFAUIgGAQIAABjgAkMBFIAAgKIgmAAIAAAKIgHAAIAAhxQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAQAAIAHgUIAGACIgGASIAYAAQABAAABAAQAAABAAAAQABAAAAABQAAAAAAABIAABxgAkyA0IAmAAIAAgqIgmAAgAkygnIAAApIAmAAIAAgpIgBgBIgkAAIgBABgAFmBFIAAgzQAAAAABgBQAAAAAAAAQAAAAABgBQAAAAAAAAIAiAAQABAAAAAAQAAABABAAQAAAAAAABQAAAAAAABIAAAjQAAAAAAABQAAAAAAABQgBAAAAAAQAAAAgBAAIgdAAIAAANgAFtAZIAAAYIAXAAQAAAAABAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAgYQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIgWAAQAAAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAABgADyA+QAPgCAMgDQAMgDAJgEIABAAQAIgEAHgGQAHgGAFgIIAGAEQgLAOgEADQgFAEgHAEIgPAGIgRAFIgVADgAhJBFIAAgfIhMAAIAAgHIAYAAIAAgxQAAAAABAAQAAgBAAAAQAAAAABAAQAAAAAAAAIAyAAIAAggIgwAAQgEAIgGAIQgGAHgHAFIgGgFQAHgFALgMIAFgKIAGgOIAHACIgEAJIBnAAIAAAHIgzAAIAAAgIAtAAIAAAHIgtAAIAAArIA2AAIAAAHIg2AAIAAAfgAh1gLIAAAqIAsAAIAAgrIgrAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAABgAjyBAIAAgIIAYAFIAIgBIAFgCQADgBACgEQACgEABgGQACgIABgZIABg2IgsAAIgFAOIgHALIgGgDIAHgNIAGgQIAAAAIADgQIAHABIgDAPIAvAAIABAAIABABIABADQAAAhgCAqQgDASgCAGQgCAFgCADQgCAEgDABIgHADIgJABQgPgCgKgDgAAsBEIAAgUIgYAAIAAgHIAYAAIAAgPIgVAAIgBgBIAAg6IABgBIAVAAIAAgOIgWAAIAAgHIAWAAIAAgNIAHAAIAAANIAXAAIAAAHIgXAAIAAAOIAWAAIABABIAAA6IgBABIgWAAIAAAPIAXAAIAAAHIgXAAIAAAUgAAzATIAPAAIABgBIAAgTIgQAAgAAdASIAAABIAPAAIAAgUIgPAAgAAzgIIAQAAIAAgTIgBAAIgPAAgAAdgbIAAATIAPAAIAAgTIgPAAgAofAqIAGgEIAJAMIAKAOIgGAEQgNgUgGgGgAo+AtIAHgCIAIAYIgHABQgCgIgGgPgAnkA9IAYgBQALgBAIgDIAOgEIgDgCIgKgJIgLgLQgQAIgKADIgDgHIAGgCQAJgDAOgIIAJgGIAFgIIgDgCQgCgCAAgCIAAgcIgiAAIAAABIAAAUIgHAAIAAgaQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIBbAAIAQgSIAFAFIgLANIAfAAQABAAAAAAQABABAAAAQAAAAAAABQAAAAAAABIgCALIgEALIgHgCIAEgPQABAAAAAAQAAAAgBgBQAAAAAAAAQAAAAgBAAIhNAAIAAAZIABACIADABIAmAAIACgBIACgKIAHACQgBALgCACQgDADgCAAIgnAAQgDAFgHAIIBAAAIAEAFIAAAAIgSAQIgUALQAIADAUADQAJABAWgBIgBAHIgSABIgRgBQgIgBgIgDIgQgGIgZAJIgRACIgWABgAmpAtIAHAEIACgBQAKgEAIgFQAJgFAGgGIg8AAQAGAHAMAKgAINA8IAMgIIALgJIAJgLIAIgMIAGgNQADgHABgGIAFghIg1AAIAAgHIA1AAIAAgWIAHAAIAAAWIBBAAIABAAIABABIAAA6IgCAWQgBAIgCAGIgFAIIgGAGQgDACgFAAIgJAAQgQgCgKgDIABgIQAKADAOADIAIAAIAGgCQAEgCADgHQACgFACgJIABgWIABgyIgBAAIg7AAIgBASIgEARIgGAQIgIARIgQAUQgOAMgIAFgABOBBIAAgHIAkAAIAAglIggAAIAAgHIBGAAIAAAHIgfAAIAAAlIAjAAIAAAHgADfA6IAAhpIAHAAIAABpgADyAqIAagGIALgFQAFgDADgDQAHgFAHgJIAFAFIgMANIgKAHIgLAFIgOAEIgPADgApLAdQAGgFAFgJQAFgJAEgMIgLgQIAGgEIAIAKIADgeIgVAAIAAgHIAVAAIAAgOIAHAAIAAAOIATAAQABAAAAAAQABAAAAAAQAAAAABAAQAAAAAAABIAAAwQABALACAJIABACIACgCIACgOIAHADIgDAPIgEAHQAAABgBAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQgFgGAAgDQgBgFgBgPIAAgrIgBgBIgOAAIgCAUIgDASQAIALAHAQIgGADIgMgVIgIASIgLAPgAqMAZIAagDIAAgQIgaAAIAAgGIAaAAIAAgOIAHAAIAAAOIAcAAIAAAGIgcAAIAAAPIAdgDIABAHIg+AHgAjqgTIAGgCQAIASAJAeIgGACQgFgQgMgggADxASQAIgBAPgGQAIgDANgJIAFAFQgPAKgIAEIgLAEIgNADgAGhARQgBAAAAAAQgBAAAAAAQAAgBAAAAQgBgBAAAAIAAgpQgGAHgFAEIgFgFQAHgGAFgHQAGgHADgIIAGACIgDAIIAcAAIAEgIIAGAEIgCAEIAjAAIAAAHIgkAAIAAAJIAjAAIAAAHIgjAAIAAAKIAjAAIAAAGIgjAAIAAAJIAlAAIAAAHgAGlAJIABABIAcAAIAAgJIgdAAgAGlgFIAdAAIAAgKIgdAAgAGlgeIAAAIIAdAAIAAgJIgcAAIAAAAIgBABgAl6gMIAFgEQANAQAGAJIgGAEQgMgRgGgIgAndAHQAFgEAFgFIAIgMIAGAEQgEAHgFAFQgFAGgGAFgABUgPQgEgFABgCQAFgFADgHIAGgPIAGADIgIARQgGAJABACQAIAMAFAKIgGAEIgLgXgABvgMQgFgIABgBQADgFADgHIAFgQIAGADIgEAOIgBAAQgGAMABACQADAEAJARIgHADQgDgKgFgIgACFgQQgDgFABgCIAGgLIAFgOIAGADIgFAOQgGAKABABQAFAHAIAOIgGAEIgMgVgAFmADIAAgGIAlAAIAAAGgADtgEQAMgDAJgDQAKgEAIgFQgHgGgFgHQgGgHgEgIIgHAKIgHAHIgFgEQAHgHAFgIIAIgTIAHABIgDAIIBBAAIAAAHIgPAAQgFALgFAIQgFAIgHAGIARAIIAVAGIgDAGQgOgDgHgDQgKgEgJgGQgJAFgKAFIgWAGgAEOgjIAMAMQAGgGAFgHQAFgHAEgJIgqAAQAEAKAGAHgAmkgQIAGgFIAJAKIgFAFgAqOgPQAJgDAEgCQAEgEAAgEIAAgGIgQAAIAAgIIAcAAIAAgLIgYAAIAAgHIAYAAIAAgHIAHAAIAAAHIAYAAIAAAHIgYAAIAAALIAcAAIAAAIIgQAAIAAAOIABACIADACQACAAAHgKIAGAFQgFAJgBAAQgEADgCAAIgHAAQgDgBgCgCQgCgCAAgDIAAgRIgRAAIAAAGIgBAFQgCAFgFADQgFAEgHACgAFmgQIAAgHIAkAAIAAAHgAmqgvIAGgFIAJAMIgGAEIgJgLgAnOgvIAGgFQAEAFAFAHIgGAEIgJgLgAFigkIAAgHIAuAAIAAAHgAHRguIAAgIIgeAAIAAAIIgHAAIAAgIIgXAAIAAgHIAXAAIAAgJIAHAAIAAAJIAeAAIAAgJIAHAAIAAAJIAYAAIAAAHIgYAAIAAAIgAnag3IAAgHIA8gBQAXgBAdgDIABAHQgYADgVABIgwABIgUAAgAFmg4IAAgHIAlAAIAAAHgABRg4IAAgHIBKAAIAAAHg");
	this.shape.setTransform(66.4,56.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ct3txt_3, new cjs.Rectangle(0.9,49.3,130.9,14.2), null);


(lib.ct3txt_2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAgBeIAAhBQAAgBAAAAQAAgBAAAAQABgBAAAAQABAAABAAIBKAAIAAgRIg/AAQAAAAAAAAQAAAAAAAAQAAgBAAAAQgBAAAAAAIAAg6QAAAAABAAQAAAAAAgBQAAAAAAAAQAAAAAAAAICHAAQABAAAAAAQAAAAAAAAQAAABAAAAQABAAAAAAIAAA6QAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAgBAAIg/AAIAAARIBLAAQABAAABAAQAAAAABABQAAAAAAABQAAAAAAABIAAAzQAAAGgEADQgFADgJABQgKgBgPgDIAAgLIAUAFQAIAAADgCQADgCAAgDIAAgoIgBgBIhEAAIAAAXIAkgDIgFgIIAIgGQAHAKAIAPIgIAFIgFgHIhjAJIgBgJIAygFIAAgYIhDAAIgBABIAAA6gAB2AAIA3AAIABAAIAAgPIg4AAgAA2AAIABAAIA2AAIAAgPIg3AAgAB2gYIA4AAIAAgRIgBgBIg3AAgAA2gpIAAARIA3AAIAAgSIg2AAgAHzBcIAAi2IAKAAIAAC2gAh0BcIAAhbIhXAAIAAgIIBXAAIAAhDIhJABIgBgKQAYABA8gCIArgCQATgCAMgCIABAKQgmAFglABIAABDIBWAAIAAAIIhWAAIAABbgAFdA0QgJAHgKAGIgWAKQgMAEgOAEQgOAEgPADIgEgMIAEAAQARgDAdgJIAogTIg+ghQAAAAAAgBQgBAAAAAAQAAgBAAAAQAAgBAAAAQAHgLAUgqIg4AAIAAgJIA7AAIAMgpIAKAFIgLAkIBxAAIAAAJIglAAIgBAFQgBAPgEANQgDALgEALQgEAKgGAIQgGAIgGAGIBIAmIgHAIgAEvgQIgNAWQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAAAABIA6AeIAAAAQAIgIAGgJQAGgJAFgKQAEgJACgMQADgMABgMIhGAAQgEANgGANgAlBBZQgJAAgMgEIAAgJQAKADAHABQAIAAACgCQABAAAAAAQABgBAAAAQAAgBAAAAQAAAAAAgBIAAiDIg5AAIAAgKIA5AAIAAgbIAKAAIAAAbIA5AAIAAAKIg5AAIAAADQABAWADALQAHAUAEALQAGAKANAUQAIAJATAUIgIAFQgZgbgIgMIgMgSIgIgRIAABMQAAAHgFACQgEADgHAAIgCAAgAIfBXIAAgJIA0AAIAAhBIgvAAIAAgJIAvAAIAAg6IgmAAIAAABQgHATgEAHIgJgDQAEgKAIgUQADgKADgVIAJABQgBAOgEAMIAkAAIAAgaIAKAAIAAAaIAuAAIAAAKIguAAIAAA6IAtAAIAAAJIgtAAIAABBIAyAAIAAAJgAqIBWIAAgJIBSAAIAAgsIg7AAIAAgJIA7AAIAAgnIhCAAIAAgKICNAAIAAAKIhCAAIAAAnIA8AAIAAAJIg8AAIAAAsIBUAAIAAAJgAl5BFQAJgIAOgQQAHgKAKgUIAIAEQgNAYgGAJQgOARgHAGgAmsBBIAYgKIAAg/IgYAAIAAgKIAYAAIAAg4IgZAAIAAgJIA9AAIAAAJIgaAAIAAA4IAZAAIAAAKIgZAAIAAA7IAUgLIAFAIQgLAHgOAGQgOAGgQAHgAHYAUQAEgTACgSQACgSAAgQIAKABQgFA1gEATgAkWgGQAIgLALgXIAIAGQgMAWgHALgAIDgyIAKgDIALAxIgKACgAlqgiIAIgHIALAQIALATIgIAEQgIgOgOgSgAqOggIAYgLIAXgOIAVgQIAUgTIAHAAIAuAjQAMAIAMAGQALAGALAEIgFAJQgKgEgMgGQgMgGgOgJIgWgQQgLgHgJgJIgVAUQgLAIgKAIQgLAHgLAFQgLAGgMAEgACSg7IAAgKIhAAAIAAAKIgJAAIAAgKIg1AAIAAgKIA1AAIAAgPIAJAAIAAAPIBAAAIAAgOIAKAAIAAAOIAzAAIAAAKIgzAAIAAAKgAkbhWIAGgHQAPALAFAEIgGAHQgKgJgKgGg");
	this.shape.setTransform(66.4,31.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ct3txt_2, new cjs.Rectangle(0.9,21.8,131,18.9), null);


(lib.ct3txt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AIxBIIAAgKIgsAAIAAAKIgHAAIAAghQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIA2AAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAAAhgAIFAsIAAAMIAsAAIAAgMIgBgBIgqAAQAAAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAgAoiBIIAAg1IgXALIgFgGQAPgGANgHIAAgpIgPAAIgDAOIgEAKIgHgBQAEgLADgMIACgYIAAgHIAHAAIAAAHIgCAQIAAABIAPAAIAAggIAHAAIAAAgIATAAIAAAHIgTAAIAAAkIANgIIAEAFIgRALIAAA6gAE/BAIASgCQAJgBAJgDQgKgFgMgHIAEgHQAKAHAQAJIAFgDIANgIQAGgEAFgFIhDAAIAAgHIBJAAIAFAEIgNAPIgRALQAJADAaACIgCAHQgKAAgJgCIgSgEIgFgCIgOAFIgNADIgQABgAByBFIAAhVIgKAOIgEgFIAIgOIAHgOQAEgHACgIIAEgSIAHACIgFAUIgGAQIAABjgAADBCIAAgHQAVAEAHgDQABAAAAgBQAAAAAAAAQABAAAAgBQAAAAAAgBIAAgNIhBAAIAKAQIgHAFQgIgQgEgFIgZAAIAAgHIBjAAIAAgLIgkAAQgIAAgHgCQgHgBgFgCQgEgCgDgDIgFgHIgEAFIgGAGQgHAEgHACIgCgHQAHgDAJgEIAEgGQABgDAAgDIAAgVQAAAAAAgBQAAAAAAAAQAAAAAAAAQgBgBAAAAIgTAAIAAgHIAaAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAAbQAAAEAEAFQAEADAHADQAFACAZABIA+AAIgBAIIgbAAIAAALIAdAAIAAAHIgdAAIAAAPQAAAFgEACQgCACgEAAIgHABQgMgBgIgCgAkuBDIABgIIANADQAGAAACgBIACgDIAAhGIgkAAQgBAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAguQAAgBAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAoAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIAAB4IgCAFIgDACQgEACgHAAQgHAAgIgCgAk1gVQAAABAAAAQAAABAAAAQABAAAAAAQAAABABAAIAdAAIAAgPIgfAAgAk1g1IAAAMIAfAAIAAgMQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAIgbAAQAAAAgBAAQAAAAAAAAQAAABAAAAQAAAAAAABgAl1BFIAAiCQAAAAAAgBQAAAAABAAQAAAAAAAAQABAAAAAAIAoAAQAAAAABAAQAAAAAAAAQAAAAABAAQAAABAAAAIAAAvQAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAIgjAAIAABRgAlugTIAcAAQAAAAABAAQAAAAABAAQAAgBAAAAQAAAAAAgBIAAgMIgeAAgAlug2IAAANIAeAAIAAgNQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAIgaAAQAAAAgBABQAAAAAAAAQAAAAgBAAQAAABAAAAgAEQBFIAAgyQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAhAAQABAAAAAAQABAAAAAAQAAAAABABQAAAAAAABIAAAjQAAABAAAAQgBABAAAAQAAAAgBAAQAAAAgBAAIgcAAIAAANgAEXAZIAAAYIAWAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIAAgYQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBgBAAIgVAAQgBAAAAABQAAAAAAAAQAAAAAAAAQAAABAAAAgACbA+QAPgCANgDQAMgCAJgFIABAAQAIgEAGgGQAHgGAGgHIAGADQgLAOgFADQgFAFgGADIgPAGIgSAFIgVADgAntBBIAAgIIATAEQAHAAAEgCQAAAAABAAQAAAAAAgBQABAAAAAAQAAgBAAAAIAAgsIg6AAIAAgHIA6AAIAAgVIg+AAIAAgHIAnAAIAAgXIgjAAIAAgHIAjAAIAAgSIAHAAIAAASIAmAAIAAAHIgmAAIAAAXIAtAAIAAAHIgWAAIAAAVIATAAIAAAHIgTAAIAAAtQAAAGgEACQgFACgIAAQgJAAgNgDgAG1A9IAJgBIAAgfIAHAAIAAAeIANgCIAAglIgVAAIgBgBIAAgZIABAAIAwAAIABAAIAAAZIgBABIgTAAIAAAOIAVAAIAAAGIgVAAIAAAQIAZgDIABAHIg+AIgAHDAOIAkAAIAAgOIgkAAgAmVBBQAPgaABgbIAHAAQgDAWgDAJQgGARgEAHgAjuBAIAJgdQACgLACgYIAHAAIgCAXIAHAMIAJAJIAAg7IggAAIAAgIIAgAAIAAgVIgaAAIAAgHIAaAAIAAgSIAHAAIAAASIAWAAIAAAHIgWAAIAAAVIAYAAIAAAIIgYAAIAAAYIAXAAIAAAGIgXAAIAAAiQAGADAOAEQAIACATAAIAyAAIgCAIIgtAAQgZgCgJgBQgGgBgGgDQgGgCgFgEQgFgDgEgFQgFgFgDgGIgEAQIgHAQgACIA6IAAhpIAHAAIAABpgAlmAzIAAgHIAhAAIAAgPIgaAAIAAgHIAaAAIAAgQIgeAAIAAgGIBDAAIAAAGIgeAAIAAAQIAaAAIAAAHIgaAAIAAAPIAgAAIAAAHgACbAqIAagGIALgFQAFgDAEgDQAGgFAHgIIAGAEIgMANIgKAHIgMAFIgNAFIgPACgAn+AbIAGgFQAIAHAJANIgFAFQgNgQgFgEgAimAvIAAgBIAAguIAAAAIA/AAIABAAIAAAuIgBABgAifAnIAxAAIABAAIAAghIgBgBIgxAAgAH0AbIAfgJIgPgLIgLAGIgDgFIAMgHQAEgDAGgIIAGABIgCADIAjAAIAEAEIgJAKQgGAGgHAEQAJADAWAFIgDAGQgIgBgJgCQgIgDgKgFQgXAJgMADgAIJACQAKAIAIAEIAKgGIAJgIIgiAAgACbASQAIgBAPgFQAHgEAOgJIAEAFQgOAKgIAEIgMAEIgMADgAFKASQAAAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAgoQgHAGgFAEIgFgFQAHgGAGgHQAFgHADgIIAHADIgDAHIAbAAIAEgHIAHADIgCAEIAjAAIAAAHIglAAIAAAJIAkAAIAAAHIgkAAIAAAKIAkAAIAAAGIgkAAIAAAKIAmAAIAAAHgAFPAKIABABIAbAAIAAgKIgcAAgAFPgFIAcAAIAAgKIgcAAgAFPgeIAAAIIAcAAIAAgJIgbAAIgBAAIAAABgAgWAKIgBgBIAAgxIABgBIAdAAIAFgKIgsAAIAAgHIAbAAIgFgGIAGgEQAEAFACAFIAeAAIAHgKIAGAFIgEAFIAaAAIAAAHIgwAAIgFAKIAtAAIABABIAAAxIgBABgAgQADIAAAAIBEAAIABAAIAAgJIhFAAgAgQgMIBFAAIAAgIIhFAAgAgQgiIAAAIIBFAAIAAgIIgBAAIhEAAgAEPADIAAgGIAmAAIAAAGgACXgEQALgDAKgDQAKgEAIgFQgHgFgGgIQgFgHgEgIIgHALIgHAGIgFgEQAGgGAGgJIAHgTIAHABIgCAIIBBAAIAAAIIgPAAQgFAKgGAIQgFAJgGAFIARAIIAVAGIgDAGQgPgDgHgDQgKgDgJgHQgIAFgKAFIgXAHgAC4giIALALQAHgGAFgGQAFgHADgJIgpAAQAEAJAGAIgAmVgWIAFgFQANAKAIAJIgFAFQgIgJgNgKgAivgJQAGgDAFgFQAFgEAEgFQAEgGACgHQADgHABgHIgZAAIAAgHIBBAAIABAAIABABIAAAYQAAAKgCAHQgBAFgDACQgEADgJAAQgIgBgMgEIAAgJQAMAFAHABQAHABADgCIACgFIABgEQABgVgBgGIgBAAIgaAAQgCAIgDAIQgCAIgEAFQgEAHgGAEQgFAFgHAEgAH3gNIAAgeIg3AAIgBABIAAASIgHAAIAAgYQAAAAAAgBQAAAAABAAQAAAAAAAAQAAgBAAAAIA+AAIAAgJIg3AAIAAgHIB0AAIAAAHIg2AAIAAAJIBAAAQABAAAAABQAAAAAAAAQAAAAAAABQAAAAAAAAIgCAXIgHgCIACgPIgBgBIg5AAIAAAegAEPgPIAAgIIAlAAIAAAIgAIHgQIAAgHIAoAAIAAAHgAHHgQIAAgHIAoAAIAAAHgAIGgdIAAgGIApAAIAAAGgAHHgdIAAgGIAoAAIAAAGgAEMgkIAAgHIAuAAIAAAHgAmUg7IAFgGQAMALAHAHIgFAFQgHgIgMgJgAhAg6IAEgFQANAIAHAHIgFAGQgHgHgMgJgAF7gtIAAgJIgfAAIAAAJIgHAAIAAgJIgWAAIAAgHIAWAAIAAgIIAHAAIAAAIIAfAAIAAgIIAHAAIAAAIIAYAAIAAAHIgYAAIAAAJgAEPg4IAAgGIAmAAIAAAGg");
	this.shape.setTransform(58.2,6.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ct3txt, new cjs.Rectangle(0.6,-0.6,115.2,14.3), null);


(lib.矩形9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgsAyIBGgyIhGgxIAKgKIBPA7IhPA8g");
	this.shape.setTransform(4.5,6);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.矩形9, new cjs.Rectangle(0,0,9.1,12.1), null);


(lib.矩形7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AsLCWIAAkrIYXAAIAAErgAsCCLIYDAAIAAkXI4DAAg");
	this.shape.setTransform(78.1,15.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.矩形7, new cjs.Rectangle(0.1,0.1,156,30), null);


(lib.矩形6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiVCSIAAkjIErAAIAAEjg");
	this.shape.setTransform(15,15.4);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.矩形6, new cjs.Rectangle(0,0.8,30.1,29.2), null);


(lib.btntxt = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// btn-txt
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhtBDIAAgWIgcAHQgOADgPACIgCgHIAMgCIAAhnIgLAAIAAgHIBNAAIAAAHIgMAAIAAB6gAiVAuIAogJIAAgYIgoAAgAiVAGIAoAAIAAgaIgoAAgAiVgbIAoAAIAAgcIgoAAgAk6BDIAAgqIg8AEIgCgHIAvgDIAEgCQgIgIgJgHIgRgJIADgGQAEABALAIIAYgXIgyAAIgBABIAAAXIgHAAIAAgeQAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAAAAAIA7AAIAAgQIg7AAIAAgGIA7AAIAAgLIAHAAIAAALIA8AAIAAAGIg8AAIAAAQIA/AAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgEAcIgHgCIADgUIgBgBIg3AAQgPARgNAKIARAMIAdgcIAFAGQgSARgOALIA2gDIgMgNIAGgDQAMAMAOATIgGAEIgKgNIgwAEIAAAqgAAwBDIAAgyQAAgBAAAAQABAAAAgBQAAAAAAAAQABAAAAAAIAhAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIAAAmQAAABAAABQgBAAAAAAQAAABgBAAQgBAAAAAAIgcAAIAAAJgAA3AXIAAAcIAWAAQABAAAAAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgbQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAgBgBAAIgVAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAABAAAAgACkA/IgEgGIgJgSIgGgWQgDgMgBgNIgCgcIgoAAIAAgHIAoAAIgBgWIAHAAIAAAWIAUAAQgGgNgEgGIAHgDQAHANAEAJIAFAAIAAAHIggAAIACAbIAEAWIAGAVIAHASQADAFACAAIABgCIABgUIAHABIgCAUQgBAHgBACQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAQgDABgEgEgAkeAqIAEgGIAVANIASAMIgEAFQgagRgNgHgAhdA+IAPgQIAOgSIgNgcIgJggIAHgCIAIAgQADAIAHAOQAFgKAHgVQADgMADgaIgtAAIAAgGIAwAAIAFACIgDAWIgFAXIgGASIgHARIALARIAPARIgHADIgMgOQgGgHgFgIQgGAJgHAIIgOAOgAFYA/IAAgIQAXAFAEgDIABgDIAAghIgvAAIAAAsIgHAAIAAgsIguAAQgBAMgCALIgHAVIgHgCQAEgKAEgUQACgJABgRIAAhBQAAgBAAAAQABgBAAAAQAAAAAAAAQABgBAAAAIBtAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAAAABIAABxQAAAFgCACQgEADgIAAQgIABgNgDgAFFAPIAvAAIAAgfIgvAAgAERAKIAAAFIAtAAIAAgfIgtAAgAFFgXIAvAAIAAgeIgBAAIguAAgAERg1IAAAeIAtAAIAAgeIgsAAIgBAAgAl6A8IAVgJQAHgFALgJIAFAFIgVAPQgNAHgGABgABcA0IATgFIAAg1IgQAAIAAgHIAnAAIAAAHIgRAAIAAAzIABAAQALgCAIgFIADAHIgUAHIgZAGgAAxACIAAgGIAjAAIAAAGgAAxgQIAAgIIAjAAIAAAIgAArgkIAAgHIAvAAIAAAHgAAyg1IAAgIIAiAAIAAAIg");
	this.shape.setTransform(38.5,7.2);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.btntxt, new cjs.Rectangle(0.6,0.4,75.9,13.5), null);


(lib.ct2txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABWBTQAMAAALgCQAMgCALgEIgcgQIAGgIQAMAJAVALIAHgDQAJgFAIgGQAIgFAGgHIhXAAIAAgJIBfAAIAHAGQgMAPgGAEQgHAGgPAIQANAEAhADIgDAJQgMAAgMgCQgMgCgMgEIgGgCIgTAHIgRADIgVABgAEbBYIAAgLQALADAGABQAHAAADgBQAAgBABAAQAAgBABAAQAAgBAAAAQAAgBAAAAIAAgZIg2AAIAAAoIgJAAIAAhyQAAgBAAgBQAAAAAAgBQABAAAAAAQABAAABAAIBCAAQABAAAAAAQABAAAAAAQABABAAAAQAAABAAABIAABmQAAAGgEADQgEADgIAAQgJAAgNgDgAECAqIA2AAIAAgZIg2AAgAECgQIAAAXIA2AAIAAgXIgBgBIg0AAgAi1BbIAAhwQgFAJgHAKIgGgIIALgRQAFgJAEgKIAHgVIAGgVIAIACIgGAaIgIAVIAACCgAAYBaIAAhCQAAAAAAgBQABgBAAAAQAAAAABgBQAAAAABAAIAsAAQAAAAABAAQABABAAAAQAAAAABABQAAABAAAAIAAAuQAAABAAABQgBAAAAABQAAAAgBABQgBAAAAAAIgmAAIAAAQgAAhAgIAAAgIAeAAQAAAAABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgeQAAAAAAgBQAAAAgBAAQAAAAAAAAQAAAAgBAAIgcAAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAgAh/BRQAUgDAQgDQAQgEALgFIACgBQAKgFAJgIQAJgHAHgKIAIAFQgOARgGAEQgHAGgJAEQgIAFgLAEIgXAGIgbAEgAlrBRIAYgDIAAidQAAgBAAAAQAAgBAAAAQABAAAAAAQABAAAAAAIBUAAQAAAAABAAQAAAAABAAQAAABAAAAQAAABAAAAIAABLQAAABAAAAQAAABAAAAQgBAAAAABQgBAAAAAAIguAAIAHAVQAEAKAGAJQANgKASgSIAGAHQgMAOgUAPQAGAIAKAIQAJAIAOAIIgHAHIgTgNQgIgHgHgHIgNgSQgFgJgEgLQgEgLgDgLIgWAAIAABNQARgEAOgEIACAJQgMAEgRADQgPAEgUACgAlKgKIBEAAQAAAAABAAQAAgBABAAQAAAAAAgBQAAAAAAgBIAAgXIhGAAgAlKhGIAAAYIBGAAIAAgYQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIhCAAQAAAAgBAAQgBAAAAAAQAAABAAAAQAAABAAAAgAmaBaIAAirIAxAAIAHAEIgSAyQgBAFABACIAJAMIAGALQADAJAAAIQAAAIgDAHQgEAHgHAEQgGADgJAAQgIgBgKgDIAAAtgAmRAiQAJAEAHABQAHABAFgCQAGgCABgFQACgEAAgGQAAgIgEgKQgEgJgJgNIgCgDIABgCIAQgwIgjAAgAp9BTQAHgGAGgJQAGgIAFgJIAIAEQgGALgHAJQgGAJgIAGgAnqA2IAIgGIALAQIAMAUIgIAEQgNgWgKgMgAo+BYQABgNgDgXIAJAAIACAkgAoWA1IAJgDQAHAYACALIgJACIgJgigAFiBWQgEAAgCgCQgFgEAAgIIAAhFIAJAAIAAAhIAigMQAPgGAKgGIAFAHIgaANQgRAHgVAHIAAAYQAAABAAABQAAABAAAAQABABAAAAQAAABAAAAQABABAEAAIAsAAQAEAAACgCQACgEgBgRIAKABIgBATQAAAGgCADQgDAEgIAAgAHKBVIAAgHIBWAAIAAgQIhHAAIAAgHIBHAAIAAgNIg9AAQgBAAAAAAQAAAAAAAAQAAAAAAgBQAAAAAAAAIAAguIABgBICDAAQABAAAAAAQAAAAAAAAQABAAAAAAQAAABAAAAIAAAuQAAAAAAAAQAAABgBAAQAAAAAAAAQAAAAgBAAIg9AAIAAANIBKAAIAAAHIhKAAIAAAQIBXAAIAAAHgAIpAjIA1AAIABgBIAAgOIg2AAgAHrAjIA1AAIAAgPIg1AAgAIpANIA2AAIAAgMIgBgBIg1AAgAHrANIA1AAIAAgNIg1AAgAiYBMIAAiKIAJAAIAACKgAh/A3QAMgCAWgGIAOgHIAMgHQAIgHAJgLIAIAGIgQAQIgNAJQgHAFgJADQgIADgJACIgUAEgAp6AlIAAgJIAdAAIAAgpIgiAAIAAgJIAiAAIAAgqIgDAAQgFAHgGAGIgPALIgGgIQAJgFANgMQAFgGAKgUIAJADIgIAPICMAAIAAAJIgVAAIAAAqIAbAAIAAAJIgbAAIAAApIAYAAIAAAJgAoLAcIAfAAIAAgpIgfAAgAowAcIAcAAIAAgpIgcAAgApUAcIAaAAIAAgpIgaAAgAoLgWIAfAAIAAgqIgfAAgAowgWIAcAAIAAgqIgcAAgApUgWIAaAAIAAgqIgaAAgAiAAXQALgBAUgHQAJgFASgLIAGAGQgTANgKAFIgQAGIgQADgABlAXQgBAAgBAAQAAgBgBAAQAAgBAAAAQAAgBAAgBIAAg1QgJAJgGAFIgHgGQAJgHAHgKQAHgJAFgLIAIADIgEAKIAkAAIAFgKIAIAFIgDAFIAuAAIAAAJIgvAAIAAAMIAuAAIAAAJIguAAIAAANIAuAAIAAAIIguAAIAAANIAxAAIAAAJgABrAMQAAAAAAABQAAAAAAAAQAAABABAAQAAAAAAAAIAkAAIAAgNIglAAgABrgHIAlAAIAAgNIglAAgABrgoIAAALIAlAAIAAgMIgkAAIAAAAIgBABgAAYAEIAAgIIAwAAIAAAIgAiEgGQAOgDANgFQANgEAKgHQgJgIgHgJQgHgJgFgLIgBADIgSAUIgHgGQAJgIAHgLQAEgFAGgUIAJACIgDAKIBVAAIAAAJIgUAAQgGAPgHAKQgHALgIAHQAJAFANAFIAbAJIgEAHQgTgDgJgEQgNgFgMgJQgLAHgNAGQgNAGgQADgAhaguQAHAJAIAGQAJgGAGgKQAHgJAEgMIg2AAQAGANAHAJgAFigGQgEAAgCgBQgFgEAAgIIAAhEIAJAAIAAAhIAhgMQAOgGAKgGIAFAIQgLAGgPAGIgkAOIAAAXQAAABAAABQAAABAAAAQABABAAAAQAAABAAAAQACABADAAIArAAQAFAAABgCQACgEABgRIAJACQAAAWgEAEQgDAEgIAAgAHLgSIAAgIIC2AAIAAAIgAAYgVIAAgJIAwAAIAAAJgAE+gwIhKAJIgDgJIAKgBQAHgMAKgbIAIADQgHAVgHAOIA0gGIgLgRIAIgEQARAbAHAOIgIAEgAHjgmIgBgBIAAgpIABgBICGAAIABABIAAApIgBABgAHsguIB1AAIAAgNIh1AAgAHshBIB1AAIAAgJIh1AAgAATgvIAAgJIA8AAIAAAJgACkg8IAAgLIgoAAIAAALIgJAAIAAgLIgdAAIAAgJIAdAAIAAgLIAJAAIAAALIAoAAIAAgLIAJAAIAAALIAfAAIAAAJIgfAAIAAALgAAYhJIAAgJIAwAAIAAAJg");
	this.shape.setTransform(64.9,8.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ct2txt2, new cjs.Rectangle(0.8,-1.1,128.1,18.5), null);


(lib.ct2txt1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGHBbIAAgOIh7AAIAAAOIgKAAIAAiqQAAgBABgBQAAAAAAgBQABAAAAAAQABgBABAAICIAAQAAAAABABQAAAAABAAQAAABAAAAQAAABAAABIAACqgAEMBEIB7AAIAAg+Ih7AAgAEMhIIAABGIB7AAIAAhHIgBAAIh4AAQgBAAAAAAQgBAAAAAAQAAAAAAABQAAAAAAAAgAngBbIAAgOIg7AAIAAAOIgJAAIAAhVQAAAAAAgBQAAgBAAAAQABgBAAAAQABAAABAAIBIAAQABAAAAAAQABAAAAABQABAAAAABQAAABAAAAIAABVgAobANIAAA3IA7AAIAAg3IgBAAIg5AAIgBAAgACZBYIAAgKIAOACQAGAAADgCQABAAAAAAQABgBAAAAQAAgBAAAAQAAgBAAAAIAAgGIhtAAIAAATIgJAAIAAg3QAAAAABgBQAAAAAAgBQAAAAABAAQAAAAABAAIB6AAQABAAAAAAQABAAAAAAQAAABAAAAQAAABAAAAIAAAtQAAAFgEADQgEADgIABIgDAAIgPgCgABFA/IBtAAIAAgKIhtAAgABFAnIAAAIIBtAAIAAgIIgBgBIhrAAgAH8BRQAMgDAVgJQAOgGAMgIQgWgWgQgcIgOANIgHgGQAHgGAHgFIAKgMIAHgOIAIgWIAIABIgCAHIBGAAQABAAABABQAAAAABAAQAAABAAAAQAAABAAABQgCAPgDAMIgHATIgKATQgFAIgGAGIgLALQALAIAOAFQAPAHARAEIgFAJQgZgHgJgFQgTgJgGgGQgOAJgPAHQgQAIgQAEgAIXgBIAMASQAHAKAHAHQAHAJAHAGIAHgHIANgOIAIgPQAEgIADgKIAGgZIhCAAQgEAKgLATgAHhBZIAAhPQgJANgHAIIgIgGIAOgRQAHgIAFgKQAFgJAEgLIAHgUIAJACQgLAggHAMIAABdgApdBZIAAhUIgeAFIgDgJIAIgBQALgJAMgRIgRgNIgRgJIAEgJIAJAGQAJgMARgbIAHAFQgOAWgLAPIATAPQAGgKAIgSIAJADQgIASgGAKQgPATgJAJIApgFIgHgUIAJgDQAKAcADANIgJACIgDgNIgYAEIAABVgAioBWIAAgKIASACIAIAAIABgCIAAgxIgnAAQAAAQgDAPQgBAPgEAPIgLgCQAFgPACgRQADgRAAgSIAAhlQAAAAAAgBQAAAAABAAQAAgBAAAAQABAAABAAIA0AAIABAAIABACIAAChQAAAEgCACQgDAEgFAAIgBAAIgZgDgAizASIAmAAIAAgpIgmAAgAizhKIAAAqIAmAAIAAgqIgBgBIgkAAIgBABgAgvBXQgDAAgDgCQgEgDABgEIAAiXIgCgBIgrAAIgBABIAABfQABALgCAJQgBAKgCAIIgHAQQgDAGgFAFIgIgFIAHgJQAEgGAFgRQACgJAAgVIAAhmIABgBIABgBIA8AAIABABIABABIAACcIAAADIAFABIAIAAIACgBQADgBAAgDQABgDAAgGIACgfIAJABQAAAfgCAIQgBAIgEAEQgDACgEAAgAmjBSIARgQIANgSIgagdQgBgCABgEIAHgZIAHgkIgTAAIAAgJIAVAAIAEgdIAJABIgEAcIAgAAQABAAAAABQABAAAAAAQAAAAAAABQAAAAAAABIgCAfIgFAaQgCANgEAKIgIAVIAUAVIgHAIIgSgVQgTAYgJAIgAmWANQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAIAUAWIAIgUIAFgWQADgNADggIgaAAQgIAngHAWgAkwBXQgKgBgOgEIABgJQAWAHAHgDQABgBABAAQAAgBAAAAQABgBAAAAQAAgBAAAAIAAiDIgeAAQgCAJgEAJQgEAIgFAIIgJgEQAGgKAIgTQAEgKADgTIAIABIgCASIBKAAIAGACIAAAAIgEAnIgJgBQADgPABgQIgjAAIAACGQAAAFgFAEQgDACgIAAIgCAAgAAVBTQAEgLAFgXQACgMABgYIAAhMQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAIA5AAIAAgXIAJAAIAAAHIBZAAIAAAIIhZAAIAAAIIBdAAQAEAAAAAEQgDAOgDAJIgJgCQAEgKABgGQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAgBgBAAIhVAAIAAAJIA5AAIAAAIIg5AAIAAAGQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABABIA9AAIABgBQACgCADgKIAIAFQgDAMgDADQgDABgEABIhFAAQgEgBAAgEIAAgNIgiAAIAAgIIAiAAIAAgJIgyAAQAAAAAAABQAAAAgBAAQAAAAAAAAQAAAAAAAAIAABCQgBAdgCANQgFAYgFAKgAqABNIAHgdIAFgbIAJACQgEAXgJAhgApHAWIAJgCIAMAxIgJADgAkBAUQgEgPgIgUIAJgEQAIAYAEAOQAGAeADARIgJABQgDgSgGgdgAliA5QAGgKALgXQAFgMAGgaIAJACQgGAbgFANIgTAigAA4AWIgBgBIAAgkIABAAICHAAIACAAIAAAkQgBAAAAAAQAAABAAAAQAAAAAAAAQgBAAAAAAgACBAPIA2AAIAAgJIg2AAgABAAPIA4AAIAAgJIg4AAgACBAAIA2AAIAAgJIg2AAgABAAAIA4AAIAAgJIg4AAgAIogKIAGgGQAKAHAZAWIgGAGIgjgdgAolgTIAAgJIBNAAIAAAJgAo2gpQAJgHASgOIAYgZIAGAAQAKAMAOALQANAMAQAKIgHAGQgVgPgIgHQgIgHgLgOQgOARgJAGQgRAPgJAGgAHLhBIAAgJIBXAAIAAgOIAJAAIAAAOIBXAAIAAAJg");
	this.shape.setTransform(64.9,8.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ct2txt1, new cjs.Rectangle(0.8,-1,128.3,18.2), null);


(lib.prod_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.prod();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.prod_1, new cjs.Rectangle(0,0,96,194), null);


(lib.ct1txt2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AHTCCQgJAAgMgEIAAgLQALAEAGABQAHABACgBQADgCAAgDIAAgTIhKAAIAAAiIgJAAIAAheQAAgBAAAAQAAgBABAAQAAAAAAAAQABAAAAAAIBYAAQAAAAABAAQAAAAABAAQAAAAAAABQAAAAAAABIAABTQAAAGgEADQgEACgHAAIgCAAgAGRBXIBKAAIAAgRIhKAAgAGRAsIAAARIBKAAIAAgRIgBgBIhIAAgADIB7QANgHALgIQAKgIAKgJIgJgPIgIgSQgEgNgGgdIgFAAQgDAhgDAOQgGAWgGARQgGAQgHAKIgJgCIAJgSIALgdIAHgdQADgOABgPQACgPAAgOIAAgZIgbAAIAAgJIBeAAIADABIAAADIgHAtIANAAIAGAEIgEAWIgHAVIgJATQgFAJgHAJIAPAPQAJAJAMAIIgHAGQgbgWgIgJQgIAJgLAIIgXAPgADsA3IAGAPQAEAHAEAGIAJgOIAIgQQAEgLAGgaIgyAAQAFAbAEAMgADVAHIAuAAIAGgoIgzAAgAJVCBIAAgbIhIAAIAAgKIBIAAIAAgUIhPAAIAAgJIAhAAIAAgbIgnAAIAAgJIAnAAIAAgaIghAAIAAgIICnAAIAAAIIgfAAIAAAaIAlAAIAAAJIglAAIAAAbIAgAAIAAAJIhQAAIAAAUIBJAAIAAAKIhJAAIAAAbgAJeA/IAnAAIAAgbIgnAAgAIwA/IAlAAIAAgbIglAAgAJeAbIAnAAIAAgaIgnAAgAIwAbIAlAAIAAgaIglAAgAFVCBIAAhSQgDALgFALQgGALgHAKIgJgDQAJgNAHgOQAGgNAEgOIgYAAIAAgJIAcAAIAAhJIAKAAIAABJIAcAAIAAAJIgaAAQAOAUAMAWIgIAFIgUglIAABWgACPCBIAAhZIgdAFIgDgJIALgCIATgXQgOgOgPgIIAEgIIAKAGQAKgRAJgTIAIAFQgLAVgKAPIAOAMIAJgPIAHgPIAJADQgIATgGAIQgNATgJAJIAkgFQgCgIgGgKIAJgDQANAdADALIgIACIgFgMIgXADIAABagAAiCBIAAgwIgfAAIAAAOIgIAAIAAh0QAAgBAAgBQAAAAABgBQAAAAAAgBQABAAABAAIAkAAIAAgZIAJAAIAAAZIAlAAQABAAABAAQAAABABAAQAAABAAAAQAAABAAABIAAB0IgJAAIAAgOIgfAAIAAAwgAArBIIAfAAIAAgmIgfAAgAADBIIAfAAIAAgmIgfAAgAArAYIAfAAIAAgmQAAgBAAAAQAAAAAAAAQAAAAgBAAQAAAAAAAAIgeAAgAADgOIAAAmIAfAAIAAgnIgeAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAAAAAABgAg4CAIAAh7IgdAAIAAgIIBDAAIAAAIIgdAAIAAB7gAn3B4IiujYIACDUIgIgBIgHABQADgjAAhhIgBhxIAFAAQAPAUBOBgIBRBkIABhnQAAhEgCgoIAIAAIAHAAQgCAZgBBeIAAB9gAmvBfQgXgYAAgmQAAgmAYgYQAXgYAlAAQAkAAAWAYQAWAYAAAlQAAAngXAZQgXAYglAAQgkAAgWgZgAmSgnQgNAIgIAMQgHAMgEANQgEANAAAPQAAATAGARQAHARAPAMQAQAMAWAAQAWAAAQgMQAPgMAHgSQAGgRAAgUQAAgUgGgQQgGgRgPgMQgQgNgWAAQgRAAgOAHgAj7BzQgDgEAAgFQAAgFADgEQAEgDAFAAQAFAAADADQAEAEAAAFQAAAFgEADQgDAEgFAAQgFAAgEgDgAiNBzIgEABQACgmAAhIIAAhtIgCgBIgmAVIgHgIIA+geIACABIgCBxQAABaACAhgABwBuIAFgZIAFgcIAJABQgHAogEAPgAhXBtQADgUACgUQACgTAAgUIAJABIgCApIgFAmgACkA5IAJgCIAIApIgKACgAgfAfIAJgBIAGBCIgJABgAF/ATIAAgJIAyAAIAAgOIgpAAIAAgKIApAAIAAgPIguAAIAAgKIAuAAIAAgKIAJAAIAAAKIAuAAIAAAKIguAAIAAAPIAsAAIAAAKIgsAAIAAAOIAxAAIAAAJgAFnAIQAEgMAHgeIAJACIgMAsgAE5ghIAJgCIALAsIgJABQgDgWgIgVgAJ6gQIAAgNIhAAAIAAANIgJAAIAAgNIgqAAIAAgJIAqAAIAAgLIAJAAIAAALIBAAAIAAgLIAKAAIAAALIAoAAIAAAJIgoAAIAAANgAhOgfIAAgJIA0AAIAAAJg");
	this.shape.setTransform(72.2,16.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ct1txt2, new cjs.Rectangle(3.1,3.5,138.3,26.1), null);


(lib.ct1txt1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABhB7IAAgKQAKACAGAAQAHABACgCQADgBAAgDIAAgeIhJAAIAAAtIgJAAIAAh5QAAgBAAAAQAAAAAAgBQABAAAAAAQABAAAAAAIAmAAIAAg6IAJAAIAAA6IAoAAQAAAAABAAQAAAAABAAQAAABAAAAQAAAAAAABIAABtQAAAGgEADQgEADgJAAIgCABQgIAAgKgDgAA0BHIBJAAIAAgaIhJAAgAA0ALIAAAZIBJAAIAAgZIgBAAIhHAAgAkEB4QAHgIAGgJQAFgIADgKIAJACIgKAWQgGAKgGAGgAjKB6QADgLADgXIAJACQgBANgFAWgAJwB7IAAgnIhjAAIAAgKIAgAAIAAhBQAAAAAAAAQAAgBAAAAQABAAAAAAQAAgBABAAIBBAAIAAgoIg+AAQgGALgIAJQgIAJgJAGIgHgFQAJgHAOgQIAHgMIAHgSIAJACIgEALICGAAIAAAKIhDAAIAAAoIA7AAIAAAKIg7AAIAAA5IBHAAIAAAKIhHAAIAAAngAI2ASIAAA4IA6AAIAAg5Ig4AAQgBAAAAAAQAAAAAAAAQgBAAAAABQAAAAAAAAgAlrB7IAAg6IgyAAIAAgJIAyAAIAAhfIgpAAIAAgKIBcAAIAAAKIgpAAIAABfIAzAAIAAAJIgzAAIAAA6gAnYB7IAAg+QAAgBAAAAQABgBAAAAQAAAAABAAQAAgBABAAIAuAAQABAAABABQAAAAAAAAQABAAAAABQAAAAAAABIAAAxQAAABAAAAQAAABgBABQAAAAgBAAQAAAAgBAAIgoAAIAAAKgAnPBFIAAAjIAgAAQABAAAAAAQAAAAABAAQAAAAAAgBQAAAAAAgBIAAgiQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAgBgBAAIgeAAQgBAAAAABQAAAAAAAAQgBAAAAAAQAAABAAAAgApJB6IgOgDQgHgCgGgEIACgKIAOAHQAHACAFAAQAFAAAEgCQAFgCAGgLIABgBQADgGABgHIABgOIgCgQIgFgRIg3AAIAAgJIAzAAQgGgMgHgLIgCgDIACgCIAmgmIhJAAIAAgJIBTAAIAEAIIAAAAIgoAoQgDADACACQAHAKAFAMIAlAAIAAAJIgiAAQAEAMACAMQACAMgBALQgCAMgEAJIgHAKQgDAEgEABQgDADgFAAIgEABIgEgBgAhzBZIAHgGQAHAHAGAIIAMAUIgHAFQgSgbgHgHgAibBcIAIgDQAIAWADAKIgJACQgDgMgHgTgAglBxIAfgIIAAhHIgdAAIAAgKIAdAAIAAgXIgVAAIAAgIIAyAAIAAAIIgVAAIAAAXIAaAAIAAAKIgaAAIAABEIAYgJIAEAIQgNAGgQAFIgiAKgAq/ByIAUgQIARgSIgfgYQgDgDABgEQAFgLAFgRIALgkIgVAAIAAgKIAWAAIAGgeIAJADIgFAbIAjAAQAAAAABABQAAAAAAAAQAAAAABABQAAAAAAAAIgBAWQgDAbgEANQgJAbgGAMIAbAVIgFAIIgcgVQgGAJgJAJQgKAJgMAJgAqlAPIgMAjQAAAAAAABQAAAAAAAAQAAAAABABQAAAAAAAAIAbAUQAGgKAEgKQAEgKADgMQADgLABgLQACgLAAgMIgfAAIgIAegAClBnIAEgNIABgBQAUARAdAAQAgAAAUgTQAVgSAAgdQAAgXgRgNQgRgNgeAAIgSABIABgCIAAgDIgBgFIATAAQAUAAAQgPQAQgPAAgXQAAgWgOgMQgPgLgVAAQgOAAgNAGQgNAGgGAJIgCABIgFgLQAWgUAhAAQAbAAASANQATANAAAbQAAApgvAQIAAACQAZACAQAMQARAOAAAZQAAAhgZAVQgaAUgmAAQgeAAgYgLgAFYBjIAEgNIACAAQAQAUAkAAQAgAAATgVQAUgUAAgdQAAgbgQgOQgRgPgZAAQgZAAgTAPIgDgCQACgYAAgeIgBg/IACgBIBuABIABABIgCAMIAAADQgSgDgcAAIg1AAIgCBdQARgLAZAAQAcAAAUARQATARAAAdQAAAigYAXQgZAXgmAAQgkAAgVgPgAgiAyIAIgBQAFAaABALIgJABQgCgVgDgQgAANBQIAFggIAJACQgBAQgEAQgAisBIQAHgHAHgMQAGgMAGgQQgHgMgIgKIAHgEIALANQACgNACgaIgbAAIAAgJIAbAAIAAgSIAJAAIAAASIAaAAQAAAAABAAQAAAAABAAQAAAAAAABQABAAAAAAIAAA+QABAPADANIABACIACgDIAEgRIAJADIgFAUQgCAHgCACQgDADgDgBQgDAAgCgDQgGgHAAgEQgCgHgBgUIAAg4IgCgBIgSAAQAAAOgCANIgEAWQAKAQAKAUIgIAFIgQgdQgEANgGALQgHALgIAIgAkBBCIAhgEIAAgVIghAAIAAgJIAhAAIAAgSIAKAAIAAASIAkAAIAAAJIgkAAIAAAUIAmgEIABAJIhRAJgAnYApIAAgKIA1AAIAAAKgAmYAkIAMgeQAGgOADgOIAIAEQgPAtgGANgAlPgRIAJgDQAPAnAFARIgJADQgEgRgQgngAkDANQALgEAFgDQAFgEAAgFIAAgIIgVAAIAAgKIAkAAIAAgPIgfAAIAAgJIAfAAIAAgJIAKAAIAAAJIAgAAIAAAJIggAAIAAAPIAlAAIAAAKIgVAAIAAARQAAABAAAAQAAABAAAAQAAABABAAQAAAAAAAAIAEACQADAAAJgLIAHAFIgIAMQgEADgDAAIgJAAQgEAAgDgDQgCgDAAgDIAAgWIgWAAIAAAIQAAADgCADQgCAFgGAFQgHAFgKADgAnZANIAAgKIA1AAIAAAKgAAhgPQAHgFAHgIIAMgSIAIAFQgGALgHAIQgHAIgJAHgABtgpIAHgGIAaAgIgIAGQgOgUgLgMgAgngVQAJgFAJgIQAJgIAIgKIAFAAQAJAIAIAGQAIAGAIAEIgFAHQgIgDgIgFIgOgOQgHAKgIAHQgIAIgJAEgAnggOIAAgJIBDAAIAAAJgAnYgnIAAgKIA0AAIAAAKg");
	this.shape.setTransform(71.2,16.9);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ct1txt1, new cjs.Rectangle(0.8,4.4,140.8,25.1), null);


(lib.bg_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.bg();
	this.instance.parent = this;
	this.instance.setTransform(-529.5,-124.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.bg_1, new cjs.Rectangle(-529.5,-124.5,1059,249), null);


(lib.cta = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.矩形9();
	this.instance.parent = this;
	this.instance.setTransform(-351.6,-19.1,1,1,0,0,0,-488.5,-28);

	this.instance_1 = new lib.btntxt();
	this.instance_1.parent = this;
	this.instance_1.setTransform(61.4,13.9,1,1,0,0,0,38.5,7);

	this.instance_2 = new lib.矩形6();
	this.instance_2.parent = this;
	this.instance_2.setTransform(-351.6,-19.1,1,1,0,0,0,-477.5,-19);

	this.instance_3 = new lib.矩形7();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-351.6,-19.1,1,1,0,0,0,-351.5,-19);
	this.instance_3.alpha = 0.648;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3},{t:this.instance_2},{t:this.instance_1},{t:this.instance}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.cta, new cjs.Rectangle(0,0,156,30), null);


// stage content:
(lib._300x250 = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// outline
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDgA3RTYMAujAAAMAAAgmvMgujAAAg");
	this.shape.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(218));

	// logo
	this.instance = new lib.logo_1();
	this.instance.parent = this;
	this.instance.setTransform(97.5,231.5,1,1,0,0,0,84.5,11.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(218));

	// 矩形 4
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("Av2E7IAAp1IftAAIAAJ1g");
	this.shape_1.setTransform(150,232,1.477,0.571);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(218));

	// ct3-txt
	this.instance_1 = new lib.ct3txt();
	this.instance_1.parent = this;
	this.instance_1.setTransform(190.3,119.1,1,1,0,0,0,67.7,52.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(163).to({_off:false},0).to({alpha:1},11).wait(44));

	// ct3-txt
	this.instance_2 = new lib.ct3txt_2();
	this.instance_2.parent = this;
	this.instance_2.setTransform(190.3,119.1,1,1,0,0,0,67.7,52.9);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(167).to({_off:false},0).to({alpha:1},10).wait(41));

	// ct3-txt
	this.instance_3 = new lib.ct3txt_3();
	this.instance_3.parent = this;
	this.instance_3.setTransform(190.3,119.1,1,1,0,0,0,67.7,52.9);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(171).to({_off:false},0).to({alpha:1},9).wait(38));

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	var mask_graphics_194 = new cjs.Graphics().p("AAkNsII1o1IA1A1Io1I1g");
	var mask_graphics_195 = new cjs.Graphics().p("ACYNsII1o1IA1A1Io1I1g");
	var mask_graphics_196 = new cjs.Graphics().p("AENNsII1o1IA1A1Io1I1g");
	var mask_graphics_197 = new cjs.Graphics().p("AGCNsII1o1IA1A1Io1I1g");
	var mask_graphics_198 = new cjs.Graphics().p("AH3NsII1o1IA1A1Io1I1g");
	var mask_graphics_199 = new cjs.Graphics().p("AJrNsII1o1IA1A1Io1I1g");
	var mask_graphics_200 = new cjs.Graphics().p("ALgNsII1o1IA1A1Io1I1g");
	var mask_graphics_201 = new cjs.Graphics().p("ANVNsII1o1IA1A1Io1I1g");
	var mask_graphics_202 = new cjs.Graphics().p("APJNsII1o1IA1A1Io1I1g");
	var mask_graphics_203 = new cjs.Graphics().p("AQ+NsII1o1IA1A1Io1I1g");

	this.timeline.addTween(cjs.Tween.get(mask).to({graphics:null,x:0,y:0}).wait(194).to({graphics:mask_graphics_194,x:65.4,y:92.9}).wait(1).to({graphics:mask_graphics_195,x:77,y:92.9}).wait(1).to({graphics:mask_graphics_196,x:88.7,y:92.9}).wait(1).to({graphics:mask_graphics_197,x:100.4,y:92.9}).wait(1).to({graphics:mask_graphics_198,x:112.1,y:92.9}).wait(1).to({graphics:mask_graphics_199,x:123.7,y:92.9}).wait(1).to({graphics:mask_graphics_200,x:135.4,y:92.9}).wait(1).to({graphics:mask_graphics_201,x:147.1,y:92.9}).wait(1).to({graphics:mask_graphics_202,x:158.7,y:92.9}).wait(1).to({graphics:mask_graphics_203,x:170.4,y:92.9}).wait(15));

	// cta_ol
	this.instance_4 = new lib.矩形7();
	this.instance_4.parent = this;
	this.instance_4.setTransform(-230.5,124.9,1,1,0,0,0,-351.5,-19);
	this.instance_4.alpha = 0.898;
	this.instance_4._off = true;

	var maskedShapeInstanceList = [this.instance_4];

	for(var shapedInstanceItr = 0; shapedInstanceItr < maskedShapeInstanceList.length; shapedInstanceItr++) {
		maskedShapeInstanceList[shapedInstanceItr].mask = mask;
	}

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(194).to({_off:false},0).wait(24));

	// cta
	this.instance_5 = new lib.cta();
	this.instance_5.parent = this;
	this.instance_5.setTransform(-230.5,125,1,1,0,0,0,-351.6,-19.1);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(211).to({_off:false},0).to({alpha:1},4).wait(3));

	// cta
	this.instance_6 = new lib.cta();
	this.instance_6.parent = this;
	this.instance_6.setTransform(-230.5,125,1,1,0,0,0,-351.6,-19.1);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(178).to({_off:false},0).to({alpha:1},11).wait(29));

	// Selective Color 1
	this.instance_7 = new lib.SelectiveColor1_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(83,84.5,1,1,0,0,0,71,52.5);
	this.instance_7.alpha = 0;
	this.instance_7.compositeOperation = "lighter";
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(163).to({_off:false},0).to({alpha:1},9,cjs.Ease.get(0.75)).wait(46));

	// product
	this.instance_8 = new lib.prod_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(528.5,117,1,1,0,0,0,65.5,100);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(134).to({_off:false},0).wait(1).to({regX:48,regY:97,x:509,y:114},0).wait(1).to({x:502.5},0).wait(1).to({x:491},0).wait(1).to({x:473.5},0).wait(1).to({x:449.3},0).wait(1).to({x:417.5},0).wait(1).to({x:377.8},0).wait(1).to({x:330.6},0).wait(1).to({x:278.1},0).wait(1).to({x:224.3},0).wait(1).to({x:174.4},0).wait(1).to({x:132.5},0).wait(1).to({x:100.4},0).wait(1).to({x:78.3},0).wait(1).to({x:65.2},0).wait(1).to({regX:65.5,regY:100,x:77.5,y:117},0).wait(68));

	// spot_light
	this.instance_9 = new lib.spot_light_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(98.5,135,1,1,0,0,0,153.5,135);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(154).to({_off:false},0).to({alpha:1},11,cjs.Ease.get(0.6)).wait(53));

	// ct2-txt-2
	this.instance_10 = new lib.ct2txt2();
	this.instance_10.parent = this;
	this.instance_10.setTransform(236.4,186.5,1,1,0,0,0,64.8,8.1);
	this.instance_10.alpha = 0;
	this.instance_10.shadow = new cjs.Shadow("rgba(19,29,55,1)",0,0,8);
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(79).to({_off:false},0).wait(1).to({regX:64.9,alpha:0.004},0).wait(1).to({x:236.3,alpha:0.018},0).wait(1).to({x:236,alpha:0.043},0).wait(1).to({x:235.6,alpha:0.081},0).wait(1).to({x:235.1,alpha:0.132},0).wait(1).to({x:234.5,alpha:0.199},0).wait(1).to({x:233.6,alpha:0.281},0).wait(1).to({x:232.7,alpha:0.378},0).wait(1).to({x:231.6,alpha:0.487},0).wait(1).to({x:230.4,alpha:0.603},0).wait(1).to({x:229.3,alpha:0.718},0).wait(1).to({x:228.2,alpha:0.826},0).wait(1).to({x:227.2,alpha:0.921},0).wait(1).to({regX:64.8,x:226.4,alpha:1},0).wait(44).to({regX:64.9,x:223.7},0).wait(1).to({x:214.5},0).wait(1).to({x:197.4},0).wait(1).to({x:170.9},0).wait(1).to({x:133.3},0).wait(1).to({x:84.4},0).wait(1).to({x:27.3},0).wait(1).to({x:-31},0).wait(1).to({x:-82.7},0).wait(1).to({regX:64.8,x:-123.6},0).to({_off:true},1).wait(71));

	// ct2-txt-1
	this.instance_11 = new lib.ct2txt1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(177.5,160.5,1,1,0,0,0,64.9,8.1);
	this.instance_11.alpha = 0;
	this.instance_11.shadow = new cjs.Shadow("rgba(19,29,55,1)",0,0,8);
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(79).to({_off:false},0).wait(1).to({alpha:0.004},0).wait(1).to({x:177.6,alpha:0.018},0).wait(1).to({x:177.9,alpha:0.043},0).wait(1).to({x:178.3,alpha:0.081},0).wait(1).to({x:178.8,alpha:0.132},0).wait(1).to({x:179.4,alpha:0.199},0).wait(1).to({x:180.3,alpha:0.281},0).wait(1).to({x:181.2,alpha:0.378},0).wait(1).to({x:182.3,alpha:0.487},0).wait(1).to({x:183.5,alpha:0.603},0).wait(1).to({x:184.6,alpha:0.718},0).wait(1).to({x:185.7,alpha:0.826},0).wait(1).to({x:186.7,alpha:0.921},0).wait(1).to({x:187.5,alpha:1},0).wait(42).to({x:185.5},0).wait(1).to({x:179.3},0).wait(1).to({x:168},0).wait(1).to({x:150.7},0).wait(1).to({x:126.4},0).wait(1).to({x:94.3},0).wait(1).to({x:54.3},0).wait(1).to({x:7.9},0).wait(1).to({x:-41.3},0).wait(1).to({x:-88.3},0).wait(1).to({x:-129.3},0).wait(1).to({x:-162.5},0).to({_off:true},1).wait(71));

	// Layer 4
	this.instance_12 = new lib.light();
	this.instance_12.parent = this;
	this.instance_12.setTransform(-44.5,126.6,0.522,0.836,0,0,0,74.5,144.5);
	this.instance_12.alpha = 0;
	this.instance_12.compositeOperation = "lighter";
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(2).to({_off:false},0).to({scaleX:1,scaleY:1,x:195.8,alpha:0.801},13,cjs.Ease.get(-1)).to({regX:74.6,scaleX:0.61,scaleY:0.85,x:408.9},4).to({_off:true},1).wait(198));

	// Layer 3
	this.instance_13 = new lib.light();
	this.instance_13.parent = this;
	this.instance_13.setTransform(-44.5,126.6,0.522,0.836,0,0,0,74.5,144.5);
	this.instance_13.compositeOperation = "lighter";
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(2).to({_off:false},0).to({scaleX:1,scaleY:1,x:195.8},13,cjs.Ease.get(-1)).to({regX:74.6,scaleX:0.61,scaleY:0.85,x:408.9},4).to({_off:true},1).wait(198));

	// prod
	this.instance_14 = new lib.prod_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(64,114,1,1,0,0,0,48,97);
	this.instance_14.alpha = 0;
	this.instance_14.compositeOperation = "lighter";
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(2).to({_off:false},0).wait(1).to({alpha:0.167},0).wait(1).to({alpha:0.333},0).wait(1).to({alpha:0.5},0).wait(1).to({alpha:0.667},0).wait(1).to({alpha:0.833},0).wait(1).to({alpha:1},0).wait(1).to({alpha:0.503},0).wait(1).to({alpha:0.292},0).wait(1).to({alpha:0.202},0).wait(1).to({alpha:0.133},0).wait(1).to({alpha:0},0).to({_off:true},1).wait(204));

	// ct1-txt-2
	this.instance_15 = new lib.ct1txt2();
	this.instance_15.parent = this;
	this.instance_15.setTransform(232.1,132.3,1,1,0,0,0,71.3,15.9);
	this.instance_15.alpha = 0;
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(11).to({_off:false},0).wait(1).to({regX:72.2,regY:16.5,x:232.9,y:132.9,alpha:0.006},0).wait(1).to({x:232.5,alpha:0.026},0).wait(1).to({x:231.8,alpha:0.062},0).wait(1).to({x:230.7,alpha:0.117},0).wait(1).to({x:229.2,alpha:0.192},0).wait(1).to({x:227.3,alpha:0.287},0).wait(1).to({x:225.1,alpha:0.397},0).wait(1).to({x:222.7,alpha:0.515},0).wait(1).to({x:220.4,alpha:0.63},0).wait(1).to({x:218.4,alpha:0.731},0).wait(1).to({x:216.7,alpha:0.816},0).wait(1).to({x:215.3,alpha:0.883},0).wait(1).to({x:214.3,alpha:0.933},0).wait(1).to({x:213.6,alpha:0.968},0).wait(1).to({x:213.2,alpha:0.989},0).wait(1).to({regX:71.3,regY:15.9,x:212.1,y:132.3,alpha:1},0).wait(41).to({regX:72.2,regY:16.5,x:210.5,y:132.9},0).wait(1).to({x:201.8},0).wait(1).to({x:184.7},0).wait(1).to({x:155.6},0).wait(1).to({x:109.2},0).wait(1).to({x:42.4},0).wait(1).to({x:-31.9},0).wait(1).to({x:-90.5},0).wait(1).to({x:-128.4},0).wait(1).to({x:-150.8},0).wait(1).to({x:-162.6},0).wait(1).to({regX:71.3,regY:15.9,x:-167.9,y:132.3},0).to({_off:true},1).wait(138));

	// ct1-txt-1
	this.instance_16 = new lib.ct1txt1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(166.8,99.1,1,1,0,0,0,71.2,16.9);
	this.instance_16.alpha = 0;
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(11).to({_off:false},0).wait(1).to({x:166.9,alpha:0.006},0).wait(1).to({x:167.3,alpha:0.026},0).wait(1).to({x:168,alpha:0.062},0).wait(1).to({x:169.1,alpha:0.117},0).wait(1).to({x:170.6,alpha:0.192},0).wait(1).to({x:172.5,alpha:0.287},0).wait(1).to({x:174.7,alpha:0.397},0).wait(1).to({x:177.1,alpha:0.515},0).wait(1).to({x:179.3,alpha:0.63},0).wait(1).to({x:181.4,alpha:0.731},0).wait(1).to({x:183.1,alpha:0.816},0).wait(1).to({x:184.4,alpha:0.883},0).wait(1).to({x:185.4,alpha:0.933},0).wait(1).to({x:186.1,alpha:0.968},0).wait(1).to({x:186.5,alpha:0.989},0).wait(1).to({x:186.8,alpha:1},0).wait(41).to({x:184.2},0).wait(1).to({x:175.6},0).wait(1).to({x:158.5},0).wait(1).to({x:129.3},0).wait(1).to({x:82.9},0).wait(1).to({x:16.2},0).wait(1).to({x:-58.1},0).wait(1).to({x:-116.7},0).wait(1).to({x:-154.6},0).wait(1).to({x:-177.1},0).wait(1).to({x:-188.9},0).wait(1).to({x:-193.2},0).to({_off:true},1).wait(138));

	// prod
	this.instance_17 = new lib.prod_1();
	this.instance_17.parent = this;
	this.instance_17.setTransform(64,114,1,1,0,0,0,48,97);

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(68).to({x:61.5},0).wait(1).to({x:52.8},0).wait(1).to({x:35.8},0).wait(1).to({x:6.6},0).wait(1).to({x:-39.8},0).wait(1).to({x:-106.6},0).wait(1).to({x:-180.9},0).wait(1).to({x:-239.5},0).wait(1).to({x:-277.4},0).wait(1).to({x:-299.8},0).wait(1).to({x:-311.6},0).wait(1).to({x:-316},0).to({_off:true},1).wait(138));

	// bg
	this.instance_18 = new lib.bg_1();
	this.instance_18.parent = this;
	this.instance_18.setTransform(529.5,125.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(65).to({x:528},0).wait(1).to({x:522.9},0).wait(1).to({x:513.4},0).wait(1).to({x:498.3},0).wait(1).to({x:475.8},0).wait(1).to({x:444},0).wait(1).to({x:400.7},0).wait(1).to({x:347.1},0).wait(1).to({x:290.8},0).wait(1).to({x:242.4},0).wait(1).to({x:206.4},0).wait(1).to({x:181.7},0).wait(1).to({x:165.8},0).wait(1).to({x:156.6},0).wait(1).to({x:152.5},0).wait(56).to({x:149.5},0).wait(1).to({x:139.4},0).wait(1).to({x:120},0).wait(1).to({x:88.6},0).wait(1).to({x:42.6},0).wait(1).to({x:-17.2},0).wait(1).to({x:-81.3},0).wait(1).to({x:-136.8},0).wait(1).to({x:-177.8},0).wait(1).to({x:-205.1},0).wait(1).to({x:-221.5},0).wait(1).to({x:-229.5},0).wait(72));

	// 色彩填色 1
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("A3bTiMAAAgnDMAu3AAAMAAAAnDg");
	this.shape_2.setTransform(150,125);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(218));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,125,1059,250);
// library properties:
lib.properties = {
	width: 300,
	height: 250,
	fps: 18,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.png?1491576406934", id:"bg"},
		{src:"images/logo.png?1491576406934", id:"logo"},
		{src:"images/prod.png?1491576406934", id:"prod"},
		{src:"images/SelectiveColor1.png?1491576406934", id:"SelectiveColor1"},
		{src:"images/spot_light.png?1491576406934", id:"spot_light"}
	],
	preloads: []
};




})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{}, AdobeAn = AdobeAn||{});
var lib, images, createjs, ss, AdobeAn;